# Dependencies
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge

# Permalinks
permalink: /article/:title/

# Setup
title: "questionable services"
tagline: "Technical writings about computing infrastructure, HTTP & security."
byline: "by Matt Silverlock"
description: "Go programming, web security and side projects."
url: http://blog.questionable.services/
baseurl: //blog.questionable.services

author:
  name: "Matt Silverlock"
  email: "matt@eatsleeprepeat.net"
  url: "https://github.com/elithrar"
  twitter: "elithrar"
  othersite: "https://vsco.co/silverlock"

plugins:
  - "jekyll-paginate"
  - "jekyll-feed"

feed:
  path: atom.xml

paginate: 5

# Custom vars
github:
  repo: https://github.com/elithrar/elithrar.github.io
