# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /article/:title/

# Setup
title:            'go, web, go'
tagline:          'On the web, Go, and building things'
description:      'Go programming, web security and side projects.'
url:              http://elithrar.github.io
baseurl:           

author:
  name:           'Matt Silverlock'
  email:          'matt@eatsleeprepeat.net'
  url:            https://github.com/elithrar
  twitter:        elithrar
  othersite:      'https://www.eatsleeprepeat.net'

paginate:         5

# Custom vars
github:
  repo:           https://github.com/elithrar/elithrar.github.io

# prose.io
prose:
  rooturl: '_posts'
  siteurl: 'http://elithrar.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose categories..."
          options:
            - name: "go"
              value: "go"
            - name: "security"
              value: "security"
            - name: "web"
              value: "web"
            - name: "meta"
              value: "meta"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

