# Dependencies
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge

# Permalinks
permalink: "/article/:title/"

# Setup
title: "questionable services"
tagline: "Technical writings about computing infrastructure, HTTP & security."
byline: "by Matt Silverlock"
description: "Technical writings about computing infrastructure, HTTP & security."
domain: "blog.questionable.services"
url: "https://blog.questionable.services/"
baseurl: ""

author:
  name: "Matt Silverlock"
  email: "matt@eatsleeprepeat.net"
  url: "https://github.com/elithrar"
  twitter: "elithrar"
  othersite: "https://vsco.co/silverlock"

plugins:
  - "jekyll-paginate"
  - "jekyll-feed"

feed:
  path: atom.xml
  url: "https://blog.questionable.services"

paginate: 5

# Custom vars
github:
  url: "https://blog.questionable.services"
  repo: https://github.com/elithrar/elithrar.github.io
