name = "blog-worker"
account_id = "d458dbe698b8eef41837f941d73bc5b3"
workers_dev = false
compatibility_date = "2023-04-05"

main = "workers/index.mjs"

# "/*" matches both "/" and all paths under /
routes = [
    { pattern = "blog.questionable.services/*", zone_name = "questionable.services" }
]

[env.staging]
workers_dev = true

[build]
command = "npm install --no-fund"

