name = "blog-worker"
type = "javascript"

routes = ["blog.questionable.services/*"]
account_id = "d458dbe698b8eef41837f941d73bc5b3"
zone_id = "efd73e4a8b362105ccef5f8a75e4061b"
workers_dev = false

[build.upload]
format = "service-worker"
