#!/usr/bin/env python3
"""Generate the blog's original, deterministic serigraph-inspired SVGs.

Run `python3 _design/generate.py` from any directory to regenerate, or append
`--check` to verify the committed output. The 32 decimal digits in seed.json
seed Python's stdlib random.Random; bounded choices change the negative-space
gaps, shape proportions, notch depth, and orientation. There is no runtime
randomness, external dependency, or copied reference artwork.
"""

import argparse
import json
from pathlib import Path
import random
import re


ROOT = Path(__file__).resolve().parents[1]
PALETTE = {
    "paper": "#ebe8e1",
    "ink": "#22221f",
    "blue": "#243fa5",
    "red": "#c53c26",
    "yellow": "#e3d875",
}


def generate(seed):
    if not isinstance(seed, str) or not re.fullmatch(r"[0-9]{32}", seed):
        raise ValueError("seed.json must contain a string of exactly 32 decimal digits")
    rng = random.Random(int(seed))
    gap = rng.randint(13, 19)
    split = rng.randint(162, 178)
    notch_y = rng.randint(94, 113)
    notch_depth = rng.randint(31, 43)
    upper_end = rng.randint(248, 263)
    blue_end = rng.randint(318, 331)
    radius = rng.randint(80, 96)
    mirror = rng.randrange(2)
    red_width = rng.randint(318, 358)
    paper_width = rng.randint(194, 232)
    footer_offset = rng.randint(118, 158)
    glyph_rotation = rng.randrange(3)
    paper, ink, blue, red = (PALETTE[key] for key in ("paper", "ink", "blue", "red"))
    right_start = split + gap
    lower_start = upper_end + gap
    red_start = blue_end + gap
    cover_transform = ' transform="translate(400 0) scale(-1 1)"' if mirror else ""
    cover = f'''<!-- Generated by _design/generate.py; seed {seed}. -->
<svg class="serigraph-cover" viewBox="0 0 400 480" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
  <rect width="400" height="480" fill="{paper}"/>
  <g{cover_transform}>
    <path fill="{ink}" d="M0 0H{split}V{notch_y}L{split-notch_depth} {notch_y+notch_depth}V{upper_end}H0Z"/>
    <path fill="{blue}" d="M{right_start} 0H400V{blue_end-radius}Q400 {blue_end} {400-radius} {blue_end}H{right_start}V{notch_y+notch_depth+gap}L{right_start+notch_depth} {notch_y+gap}H{right_start}Z"/>
    <path fill="{ink}" d="M0 {lower_start}H{split-radius}Q{split} {lower_start} {split} {lower_start+radius}V480H0Z"/>
    <path fill="{red}" d="M{right_start} {red_start}H400V480H{right_start+radius}Q{right_start} 480 {right_start} {480-radius}Z"/>
  </g>
</svg>
'''
    footer_gap = gap - 2
    paper_start = red_width + footer_gap
    blue_start = paper_start + paper_width + footer_gap
    bottom_split = red_width + footer_offset
    bottom_red = 1010 - footer_offset
    footer = f'''<!-- Generated by _design/generate.py; seed {seed}. -->
<svg class="serigraph-footer" viewBox="0 0 1200 100" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" preserveAspectRatio="xMidYMid slice">
  <rect width="1200" height="100" fill="{ink}"/>
  <path fill="{red}" d="M0 0H{red_width-44}Q{red_width} 0 {red_width} 44H0Z"/>
  <path fill="{paper}" d="M{paper_start} 0H{paper_start+paper_width}V44H{paper_start+44}Q{paper_start} 44 {paper_start} 0Z"/>
  <path fill="{blue}" d="M{blue_start} 0H1200V44H{blue_start}Z"/>
  <path fill="{paper}" d="M0 56H{bottom_split-44}Q{bottom_split} 56 {bottom_split} 100H0Z"/>
  <path fill="{blue}" d="M{bottom_split+footer_gap} 56H{bottom_red-footer_gap}V100H{bottom_split+footer_gap}Z"/>
  <path fill="{red}" d="M{bottom_red+44} 56H1200V100H{bottom_red}Q{bottom_red} 56 {bottom_red+44} 56Z"/>
</svg>
'''
    glyph = f'''<!-- Generated by _design/generate.py; seed {seed}. -->
{{%- assign serigraph_variant = include.index | default: 0 | plus: {glyph_rotation} | modulo: 3 -%}}
<svg class="serigraph-glyph" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
  {{%- case serigraph_variant -%}}
  {{%- when 0 -%}}
  <path fill="currentColor" d="M8 8H69Q112 8 112 51V112H67V69H8ZM8 79H53V112H8Z"/>
  {{%- when 1 -%}}
  <path fill="currentColor" d="M8 8H112V48L84 72L112 96V112H59Q8 112 8 61Z"/>
  {{%- else -%}}
  <path fill="currentColor" d="M8 8H67Q112 8 112 53H8ZM8 67H112V112H53Q8 112 8 67Z"/>
  {{%- endcase -%}}
</svg>
'''
    params = {
        "gap": gap,
        "split": split,
        "notch_y": notch_y,
        "notch_depth": notch_depth,
        "upper_end": upper_end,
        "blue_end": blue_end,
        "radius": radius,
        "mirror": mirror,
        "red_width": red_width,
        "paper_width": paper_width,
        "footer_offset": footer_offset,
        "glyph_rotation": glyph_rotation,
    }
    metadata = (
        "# Generated by _design/generate.py. Do not edit by hand.\n"
        f'seed: "{seed}"\n'
        "generator: _design/generate.py\n"
        "palette:\n"
        + "".join(f'  {name}: "{color}"\n' for name, color in PALETTE.items())
        + "parameters:\n"
        + "".join(f"  {name}: {value}\n" for name, value in params.items())
    )
    return {
        "_data/serigraph.yml": metadata,
        "_includes/serigraph-cover.svg": cover,
        "_includes/serigraph-footer.svg": footer,
        "_includes/serigraph-glyph.svg": glyph,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files differ")
    args = parser.parse_args()
    seed = json.loads((ROOT / "_design/seed.json").read_text())["seed"]
    stale = []
    for filename, content in generate(seed).items():
        path = ROOT / filename
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(filename)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        parser.exit(1, "Regenerate stale output: " + ", ".join(stale) + "\n")
    print("Generated files match the seed." if args.check else "Generated four serigraph files.")


if __name__ == "__main__":
    main()
